spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/MicroServicios?allowPublicKeyRetrieval=true&useSSL=false
    username: fernando
    password: admin2022
    driver-class-name: com.mysql.jdbc.Driver
  sql:
    init:
      mode: always
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
