spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/MicroServicios?allowPublicKeyRetrieval=true&useSSL=false
    username: fernando
    password: admin2022
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 60000

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    
logging:
  level:
   '[com.ids.practica1.servicio_login]': DEBUG
  pattern:
    console: "%p, %d{'yyyy-MM-dd HH:mm:ss.SSS',America/Mexico_City}, %C{1}:%M:%L, %m%n"
