spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/MicroServicios?allowPublicKeyRetrieval=true&useSSL=false
    username: fernando
    password: admin2022
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true

resilience4j:
  circuitbreaker:
    configs:
      shared:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 10
        slow-call-rate-threshold: 10
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
        
#cards-client:
#  ribbon:
#    listOfServers: http://localhost:8082,http://localhost:8083
#    ServerListRefreshInterval: 15000
    
logging:
  level:
    '[com.microservices.account]': debug 
   
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: full  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
