spring:
  cloud:
    gateway:
      routes:
      - id: service-authenticate
        uri: lb://service-authenticate
        predicates:
        - Path=/*/authenticate/**
      - id: service-account
        uri: lb://service-account
        predicates:
        - Path=/*/accounts/**

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    
logging:
  level:
   '[com.microservices.gateway]': DEBUG
  pattern:
    console: "%p, %d{'yyyy-MM-dd HH:mm:ss.SSS',America/Mexico_City}, %C{1}:%M:%L, %m%n"